#!/usr/bin/env bash
#PBS -N gHapCall_<NUMBER>
#PBS -l select=1:ncpus=4:mem=36gb,walltime=160:00:00
#PBS -o gHapCall_<NUMBER>.out
#PBS -e gHapCall_<NUMBER>.err

BASE_DIR="/scratch1/jboatw2/SAP"
REFERENCE="${BASE_DIR}/data/references/Sbicolor_454_v3.0.1.fa"
OUTPUT_PATH="${BASE_DIR}/results/gvcfs"
TMP_DIR="${BASE_DIR}/tmp"
CHROM=10

DESIGN_FILE="${BASE_DIR}/doc/CUSo.unique.txt"
DESIGN=$(cat ${DESIGN_FILE} | head -n <NUMBER> | tail -n 1)

IFS=',' read -ra ARRAY <<< "${DESIGN}"

PI_NAME=${ARRAY[0]}

if [ ! -e ${OUTPUT_PATH} ]
then
    mkdir -p ${OUTPUT_PATH}
fi

if [ ! -e ${TMP_DIR} ]
then
    mkdir -p ${TMP_DIR}
fi

# samtools view -H ${BASE_DIR}/results/marked_duplicates/${PI_NAME}.duplicate_marked.sorted.bam  | \
#     sed "s/SM:[^\t]*/SM:${PI_NAME}/g" | \
#     samtools reheader - ${BASE_DIR}/results/marked_duplicates/${PI_NAME}.duplicate_marked.sorted.bam > \
#     ${BASE_DIR}/results/single_sample_bams/${PI_NAME}.renamed.bam

# samtools index ${BASE_DIR}/results/final_alignments/${PI_NAME}.bam

while [ ${#CHROM} -ne 2 ]
do
    CHROM="0"${CHROM}
done

~/gatk-4.1.7.0/gatk --java-options "-Xms20g -Xmx34g -XX:+UseParallelGC -XX:ParallelGCThreads=2" HaplotypeCaller \
--reference=${REFERENCE} \
--input=${BASE_DIR}/results/final_alignments/${PI_NAME}.bam \
--output=${OUTPUT_PATH}/${PI_NAME}.Chr${CHROM}.vcf.gz \
--emit-ref-confidence GVCF \
--intervals Chr${CHROM} \
--tmp-dir=${TMP_DIR}

